### PR TITLE
Update the glib package and the related dependencies

### PR DESCRIPTION
**Pull request by sayanchowdhury**
# Update the glib package and the related dependencies

This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/669.

# How to use

```
./update_chroot
emerge-amd64-usr glib
```

# Testing done

- I've tested the changes locally.
- I've triggered a Jenkins build: http://localhost:9091/job/os/job/manifest/1258/cldsv/.
  - Final build that passed: http://localhost:9091/job/os/job/manifest/1350/cldsv/ (toolchains) http://localhost:9091/job/os/job/manifest/1353/cldsv/ (sdk)

### CODE REVIEW

**Comment by dongsupark** [comment]
rebased

**Comment by dongsupark** [comment]
CI failed because of some mysterious dependency issues.

```
emerge: there are no ebuilds to satisfy "sys-libs/libxcrypt[system(-),static-libs(-)?,abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_riscv_lp64d(-)?,abi_riscv_lp64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]".
(dependency required by "virtual/libcrypt-2::portage-stable" [ebuild])
(dependency required by "@__auto_slot_operator_replace_installed__" [argument])
```

It used to be warnings due to mismatch between libcrypt slots.
However, in this case, somehow `dev-libs/glib` seems to trigger `@__auto_slot_operator_replace_installed__`, so it is not a warning any more, but an error.

Let's not merge it for now. Looking...

**Comment by dongsupark** [comment]
Figured out the issue, a slot conflict.

```
 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

 (dev-libs/glib-2.64.5:2/2::portage-stable, ebuild scheduled for merge) pulled in by
  >=dev-libs/glib-2.58.3:2 required by (dev-util/gdbus-codegen-2.58.3:0/0::portage-stable, binary scheduled for merge)

 (dev-util/gdbus-codegen-2.58.3:0/0::portage-stable, binary scheduled for merge) pulled in by
   dev-util/gdbus-codegen required by (coreos-base/hard-host-depends-0.0.1-r194:0/0::coreos, binary scheduled for merge)
```

Pushed a fix.

Also we need to update coreos-overlay.
Created a PR https://github.com/flatcar-linux/coreos-overlay/pull/657.
Let me trigger CI.

**Comment by dongsupark** [comment]
No, it still fails because the catalyst stage1 still relies on the previous SDK build with gdbus 2.58.3.

We need to take 2 steps, the first is to update meson and gdbus-codegen in a release, and the second is to update glib in the next release.
I will split the meson / gdbus-codegen part into another PR.

**Comment by dongsupark** [comment]
Split out https://github.com/flatcar-linux/coreos-overlay/pull/658.

**Comment by dongsupark** [comment]
SDK for Alpha 2671.0.0 was released with meson 0.55.3 and gdbus-codegen 2.64.5.

However, this PR is still in progress, because it still has conflicts with dbus-glib and glib-utils.
Updated the 2 packages, and running an SDK build.

**Comment by dongsupark** [comment]
CI passed finally.
@sayanchowdhury Please have a look.

**Comment by dongsupark** [comment]
Oh, I have just realized, the new `dbus-glib` 0.110 breaks the ARM builds.
We need to move the dbus-glib part to coreos-overlay, so we can apply the existing 3rd-party patch on top of 0.110.

**Comment by dongsupark** [comment]
Split out https://github.com/flatcar-linux/coreos-overlay/pull/669.
Running another CI builds.

**Comment by dongsupark** [comment]
CI passed.

**Comment by sayanchowdhury** [comment]
Looks good to me.

**Pull request merged**
