### PR TITLE
app-arch/zstd: Import from Gentoo

### PR DESCRIPTION
**Pull request by krnowak**
An updated systemd will need it.

Just did a sync of systemd to latest ebuild from Gentoo and there is a new USE flag, enabled by default, `zstd`. This pulls a dep on the `app-arch/zstd` package, which I'm adding here.

http://localhost:9091/job/os/job/manifest/1300/

### CODE REVIEW

**Comment by vbatts** [comment]
zstd is going to be nice to have around

**Review by dongsupark — APPROVED** [review]
Looks good if CI passed.

Nit: it would be nice to have `zstd` in the PR title.

**Comment by krnowak** [comment]
> Looks good if CI passed.
> 
> Nit: it would be nice to have `zstd` in the PR title.

Oooops, I meant to have it in the title. Fixed.

**Comment by krnowak** [comment]
Test build passed, merging.

**Pull request merged**
