### PR TITLE
Get rid of EAPI 0

### PR DESCRIPTION
**Pull request by krnowak**
For some background, see the coreos-overlay PR.

Not all EAPI 0 packages are actually updated here, as some of those are a part of [EAPI4 removal](https://github.com/flatcar-linux/portage-stable/pull/246), so I avoided the duplication here.

Had to update profiles and sys-devel/autotools and a related eclass to fix issues with sys-devel/autotools-wrapper.

To be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/1525.

CI: http://localhost:9091/job/os/job/manifest/4592/cldsv/

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [x] https://github.com/flatcar-linux/portage-stable/pull/268 is merged

### CODE REVIEW

**Comment by krnowak** [comment]
This seems to need some eclass update which is also a part of #262, so let's wait for the other PR to be merged.

**Comment by krnowak** [comment]
Scratch that, seems to be an eclass unrelated to #262.

**Comment by krnowak** [comment]
Updated profilfes directory seems to cause some grief with lib(x)crypt stuff, so this PR is currently blocked on #267.

**Comment by krnowak** [comment]
CI passed.

**Review by tormath1 — APPROVED** [review]
It looks good to me. Checked for new useflags and so on. Nothing seems suspicious :D

**Pull request merged**
