### PR TITLE
dev-lang/perl: upgrade to 5.34.0

### PR DESCRIPTION
**Pull request by tormath1**
Upgrading Perl is required to pull `opensslv3` but it can be done independently.

## Testing done

jenkins all-full (:large_blue_circle: with `minimal` useflag): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3603/cldsv/

To be merged with: https://github.com/flatcar-linux/coreos-overlay/pull/1288
Related to: https://github.com/flatcar-linux/Flatcar/issues/418

### CODE REVIEW

**Comment by krnowak** [comment]
Should `virtual/perl-Encode` be moved to overlay? Or maybe there's an older version in gentoo that is still using EAPI 7?

**Comment by tormath1** [comment]
@krnowak I'll have a look regarding this ebuild. I'm waiting for the CI to pass, then I'll try to enable the new `minimal` useflag for perl-5.34: if it works `virtual/perl-Encode` won't be necessary anymore.

**Comment by tormath1** [comment]
CI is OK. I'm trying now to build a full SDK + toolchain with `minimal` useflag. In the meantime, `dev-lang/perl` has been marked as as stable for `amd64` and `arm64`

**Review by krnowak — APPROVED** [review]
CI passed, let's get this in.

**Pull request merged**
