### PR TITLE
dev-embedded/u-boot-tools: Update to 2021.04_rc2

### PR DESCRIPTION
**Pull request by aniruddha2000**
# dev-embedded/u-boot-tools: Update to 2021.04_rc2

Current Flatcar portage doesn't support the EAPI 8. So updating dev-embedded/u-boot-tools to the latest version that supports EAPI 7 which is 2021.04_rc2.

## How to use

`emerge-amd64-usr dev-embedded/u-boot-tools`

## Testing done

CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4148/cldsv

### CODE REVIEW

**Comment by aniruddha2000** [comment]
@dongsupark should I drop the v2019.10, v2020.01, v2020.04, 2020.04-r1, v2020.04-r2 ?
and keep the latest v2021.04_rc2 with EAPI 7?

**Comment by aniruddha2000** [comment]
[Here](https://github.com/flatcar-linux/coreos-overlay/pull/1414) is the updated keyword for the new package.

**Comment by dongsupark** [comment]
Thanks, it looks good, without EAPI issues.
Will soon run a CI build from the PRs.

**Comment by dongsupark** [comment]
CI passed

**Review by krnowak — APPROVED** [review]
Looks good.

**Review by dongsupark — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
