### PR TITLE
upgraded libgcrypt to 1.9.4

### PR DESCRIPTION
**Pull request by ArkaprabhaChakraborty**
libgcrypt upgraded to 1.94.0 .

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
Thanks a lot @ArkaprabhaChakraborty for the PR.

**Review by sayanchowdhury — CHANGES_REQUESTED** [review]
Few comments:
- There is a typo in the commit message, the version should be 1.9.4
- It would be good to follow the git commit guidelines: https://chris.beams.io/posts/git-commit/
- You would also need to update the accept_keywords file in the coreos-overlay: https://github.com/flatcar-linux/coreos-overlay/blob/main/profiles/coreos/base/package.accept_keywords#L103

**Comment by ArkaprabhaChakraborty** [comment]
> Few comments:
> 
>     * There is a typo in the commit message, the version should be 1.9.4

Yes. sorry about that!  :(

>     * It would be good to follow the git commit guidelines: https://chris.beams.io/posts/git-commit/

this commit message can't be changed I guess

>     * You would also need to update the accept_keywords file in the coreos-overlay: https://github.com/flatcar-linux/coreos-overlay/blob/main/profiles/coreos/base/package.accept_keywords#L103

So I create another fork of coreos-overlay and do it as usual ? or a direct update without using the sdk will do (of course by creating my own branch)?

**Comment by sayanchowdhury** [comment]
> 
> Yes. sorry about that! :(

No worries, it's all part of the learning. 
 
> this commit message can't be changed I guess
> 

You can do:
```
git commit --am
git push -f <remote> <branch>
```


> 
> So I create another fork of coreos-overlay and do it as usual ? or a direct update without using the sdk will do (of course by creating my own branch)?

Yes, you would need to create a fork of the `coreos-overlay`, then inside your sdk go to the coreos-overlay directory and add your git repo URL as a remote. This way you can test your changes before creating the PR.

Feel free drop on the matrix channel if you have doubts.

**Comment by sayanchowdhury** [comment]
Jenkins CI: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3720/cldsv/

**Review by sayanchowdhury — APPROVED** [review]

**Pull request merged**
