### PR TITLE
bump(sys-libs/libseccomp): sync with upstream

### PR DESCRIPTION
**Pull request by alban**
Update libsseccomp from Gentoo:
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/libseccomp/libseccomp-2.5.0.ebuild

Python check changed to python3_6 so it builds in Flatcar.

# How to use

To fully test libseccomp 2.5.0 with the Seccomp Notify feature, we need Linux 5.9-rc1. But basic non-regression tests can be done as follows.

# Testing done

After building a Flatcar image:
```
Flatcar Container Linux by Kinvolk developer (2605.0.0+2020-09-26-1247)
core@localhost ~ $ ldd /run/torcx/unpack/docker/bin/runc 
	linux-vdso.so.1 (0x00007fff6adeb000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f877e7c9000)
	libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f877e7a7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f877e5cf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f877f1b2000)
core@localhost ~ $ ls -l /lib64/libseccomp.so* 
lrwxrwxrwx. 1 root root     19 Sep 26 13:01 /lib64/libseccomp.so -> libseccomp.so.2.5.0
lrwxrwxrwx. 1 root root     19 Sep 26 13:01 /lib64/libseccomp.so.2 -> libseccomp.so.2.5.0
-rwxr-xr-x. 1 root root 132968 Sep 26 12:35 /lib64/libseccomp.so.2.5.0
```

Then, I tested `/run/torcx/unpack/docker/bin/runc` both with and without a seccomp profile:
- Prepare a `rootfs` and `config.json` following instructions on https://github.com/opencontainers/runc#using-runc
- Run `/run/torcx/unpack/docker/bin/runc run c1`
- Check `cat /proc/self/status|grep -i seccomp` in the container: 2 when seccomp is enabled in config.json, or 0 when not enabled
- Test the following seccomp profile in `config.json`:
```
    "seccomp": {
      "defaultAction": "SCMP_ACT_ALLOW",
      "architectures": [
        "SCMP_ARCH_X86",
        "SCMP_ARCH_X32"
      ],
      "syscalls": [
        {
          "names": [
            "fchmod",
            "chmod"
          ],
          "action": "SCMP_ACT_ERRNO"
        }
      ]
    },
```
And check if it is enforced:
```
/ # touch /dev/shm/file
/ # chmod 777 /dev/shm/file
chmod: /dev/shm/file: Operation not permitted
```

---

Fixes https://github.com/flatcar-linux/Flatcar/issues/200

### CODE REVIEW

**Comment by marga-kinvolk** [comment]
I've triggered a build in Jenkins (os/manifest 1119) to test this change.

**Comment by marga-kinvolk** [comment]
This failed with:

```
The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by sys-apps/systemd-245-r3::coreos[seccomp]
# required by app-misc/ca-certificates-3.27.1-r1::coreos
# required by dev-libs/openssl-1.1.1g::coreos
# required by net-misc/rsync-3.2.3::portage-stable[-libressl,ssl,-static]
# required by sys-apps/portage-2.3.40-r1::coreos[-build]
# required by app-admin/perl-cleaner-2.27::portage-stable
# required by dev-lang/perl-5.26.2::portage-stable
# required by sys-apps/help2man-1.45.1::portage-stable
# required by sys-devel/automake-1.16.1-r1::portage-stable
# required by dev-libs/libxml2-2.9.8::portage-stable
# required by x11-misc/shared-mime-info-1.4::portage-stable
# required by dev-libs/gobject-introspection-1.40.0-r1::portage-stable
# required by sys-auth/polkit-0.113-r5::coreos[introspection]
=sys-libs/libseccomp-2.5.0 ~amd64
```

**Comment by marga-kinvolk** [comment]
As clarified on slack: 
The error means that the package is masked for the architecture we're trying to build it for.
We need to unmask the package, either by changing ~amd64 ~arm64 to amd64 arm64 in the package ebuild file, or by unmasking in https://github.com/flatcar-linux/coreos-overlay/blob/main/profiles/coreos/base/package.accept_keywords

**Comment by alban** [comment]
Unmasking done in https://github.com/flatcar-linux/coreos-overlay/pull/621

**Comment by dongsupark** [comment]
Looks good in general.
Build seems to work for both amd64 and arm64.

Not so great that libseccomp 2.5 started pulling in `gperf`, but we can do nothing about that. I think it is ok as gperf takes quite small space.

I have not run Jenkins builds. To do that, the branch name in coreos-overlay should probably match with `alban/update-seccomp` of this PR.

**Comment by alban** [comment]
Should I rename the branch and create a new PR with the renamed branch?

**Comment by marga-kinvolk** [comment]
No, the branch name doesn't matter. I'll start a Jenkins build with both branches.

**Review by marga-kinvolk — APPROVED** [review]
LGTM, tests passed

**Review by dongsupark — APPROVED** [review]

**Pull request merged**
